server:
  port: 8082

spring:
  application:
    name: product

eureka:
  instance:
    prefer-ip-address: true   # OS에서 제공하는 hostname 대신 자신의 ip address를 사용하여 등
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka # default address